# Generated by Django 3.0.7 on 2021-03-30 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_auto_20210323_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmpreportecontrolpatronsustitutodetalle',
            name='raiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='app.TmpReporteControlPatronSustituto'),
        ),
    ]
