# Generated by Django 3.0.7 on 2021-03-30 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_auto_20210330_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmpreportecontrolinscritosmod40',
            name='fecha_de_alta',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
