# Generated by Django 3.0.7 on 2021-04-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_auto_20210405_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmpestatusenvio',
            name='medio',
            field=models.CharField(max_length=50, verbose_name='Estatus de Envío'),
        ),
        migrations.AlterField(
            model_name='tmpproxevt',
            name='medio',
            field=models.CharField(max_length=50, verbose_name='Tipo de Evento'),
        ),
    ]
