# Generated by Django 3.0.7 on 2021-04-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_auto_20210409_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='TmpMedioPensPso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['medio'],
            },
        ),
        migrations.CreateModel(
            name='TmpMedioTramCorr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['medio'],
            },
        ),
        migrations.CreateModel(
            name='TmpTipoTramCorr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio', models.CharField(max_length=50, verbose_name='Tipo de Tramite')),
            ],
            options={
                'ordering': ['medio'],
            },
        ),
    ]
