# Generated by Django 3.0.7 on 2021-04-16 19:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_tmpmediopenspso_tmpmediotramcorr_tmptipotramcorr'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmpreportpensionesenproceso',
            name='concluido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tmpreportpensionesenproceso',
            name='fecha_de_correccion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='tmpreportpensionesenproceso',
            name='fecha_de_envio_p',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='tmpreportpensionesenproceso',
            name='prorroga_o_incorformidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tmpreportpensionesenproceso',
            name='medio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.TmpMedioPensPso'),
        ),
        migrations.AlterField(
            model_name='tmpreporttramitesycorrecciones',
            name='medio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.TmpMedioTramCorr'),
        ),
        migrations.AlterField(
            model_name='tmpreporttramitesycorrecciones',
            name='tipo_de_tramite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.TmpTipoTramCorr'),
        ),
        migrations.DeleteModel(
            name='TmpReportPensionesEnProcesoDetalle',
        ),
    ]
