# Generated by Django 3.0.7 on 2021-04-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_auto_20210416_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmpreportpensionesenproceso',
            name='fecha_de_correccion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tmpreportpensionesenproceso',
            name='fecha_de_envio',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tmpreportpensionesenproceso',
            name='fecha_de_envio_p',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tmpreportpensionesenproceso',
            name='fecha_de_pago_inicial',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tmpreportpensionesenproceso',
            name='fecha_de_retiro_total',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tmpreporttramitesycorrecciones',
            name='fecha_de_conclusion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tmpreporttramitesycorrecciones',
            name='fecha_de_envio',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tmpreporttramitesycorrecciones',
            name='fecha_de_liquidacion',
            field=models.DateField(null=True),
        ),
    ]
