# Generated by Django 3.0.7 on 2021-05-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_auto_20210422_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='TmpEstatusPensPso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio', models.CharField(max_length=50, verbose_name='Estatus')),
            ],
            options={
                'ordering': ['medio'],
            },
        ),
        migrations.CreateModel(
            name='TmpEstatusTramCorr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio', models.CharField(max_length=50, verbose_name='Estatus')),
            ],
            options={
                'ordering': ['medio'],
            },
        ),
    ]
