# Generated by Django 3.0.7 on 2021-05-04 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_tmpestatuspenspso_tmpestatustramcorr'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmpreportpensionesenproceso',
            name='comentarios',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tmpreportpensionesenproceso',
            name='estatus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.TmpEstatusPensPso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tmpreporttramitesycorrecciones',
            name='comentarios',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tmpreporttramitesycorrecciones',
            name='estatus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.TmpEstatusTramCorr'),
            preserve_default=False,
        ),
    ]
