# Generated by Django 3.0.7 on 2022-07-27 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_auto_20220727_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estatusactividad',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='estatusactividad',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='estatusactividad',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='estatusactividad',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='externo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='externo',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='externo',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='externo',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='medioactividad',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='medioactividad',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='medioactividad',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='medioactividad',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='taxonomiaexpediente',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='taxonomiaexpediente',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='taxonomiaexpediente',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='taxonomiaexpediente',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='tipoactividad',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tipoactividad',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tipoactividad',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='tipoactividad',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='tipodocumento',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tipodocumento',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tipodocumento',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='tipodocumento',
            name='updated_by',
        ),
    ]
