# Generated by Django 3.0.7 on 2022-09-06 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_auto_20220727_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acuerdo',
            fields=[
                ('idacuerdo', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=250)),
                ('acuerdo', models.TextField()),
                ('aceptado', models.BooleanField(default=False)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('fechaHora', models.DateTimeField(null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='app.Cliente')),
            ],
        ),
    ]
