# Generated by Django 3.0.14 on 2022-10-18 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_acuerdo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acuerdo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acuerdos', to='app.Cliente'),
        ),
        migrations.AlterField(
            model_name='acuerdo',
            name='fechaHora',
            field=models.DateTimeField(null=True, verbose_name='Fecha de Aceptación'),
        ),
        migrations.AlterField(
            model_name='acuerdo',
            name='ip',
            field=models.GenericIPAddressField(null=True, verbose_name='IP de aceptación'),
        ),
    ]
