# Generated by Django 3.0.14 on 2022-10-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0075_auto_20221018_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incrementomodalidad40',
            name='monto',
        ),
        migrations.AddField(
            model_name='incrementomodalidad40',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
