# Generated by Django 3.0.14 on 2022-11-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0077_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fecha_de_pago',
            field=models.DateTimeField(null=True),
        ),
    ]
