# Generated by Django 3.0.14 on 2022-11-01 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0078_auto_20221101_1108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ['estatus', 'fecha_de_pago', 'idpago']},
        ),
    ]
