# Generated by Django 3.0.14 on 2022-11-01 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0080_auto_20221101_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acuerdo',
            options={'ordering': ['titulo', 'aceptado', 'fechaHora']},
        ),
        migrations.RemoveField(
            model_name='pago',
            name='codigo',
        ),
    ]
