# Generated by Django 3.0.14 on 2022-11-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0081_auto_20221101_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='cuenta',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estatus',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Pago'), ('pagado', 'Pagado')], default='pendiente', max_length=20),
        ),
    ]
