# Generated by Django 3.0.14 on 2022-11-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0082_auto_20221108_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='estatus',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Pago'), ('pagado', 'Pagado'), ('verificado', 'Pagado y Verificado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_de_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
