# Generated by Django 3.0.14 on 2022-11-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0083_auto_20221108_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='cuenta',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('daniel azteca', 'Daniel Azteca'), ('daniel banamex', 'Daniel Banamex'), ('sosa del bosque', 'Sosa del Bosque')], default='efectivo', max_length=50),
        ),
    ]
