# Generated by Django 3.0.14 on 2024-02-28 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0085_auto_20240228_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='conyuge',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='estado_civil',
        ),
    ]
