# Generated by Django 3.0.14 on 2024-02-28 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0086_auto_20240228_1205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ['-fecha_de_pago', '-estatus', 'idpago']},
        ),
    ]
